apiVersion: v1
kind: Service
metadata:
  name: eventify-api-service
spec:
  selector:
    app: eventify-api
  type : ClusterIP
  ports:
    - protocol: TCP
      port: 8027
      targetPort: 8027
      #nodePort: 30000